# question 1

In [3]:
import numpy as np 
rating = np.array([
    [4.5,5,4.3,3.2,5],
    [4.3,5,3.3,2.5,5],
    [4.6,3.2,4.9,4.8,4],
    [4.5,4.6,4.8,4.3,4.2]
                  ])
rating[1:3]

array([[4.3, 5. , 3.3, 2.5, 5. ],
       [4.6, 3.2, 4.9, 4.8, 4. ]])

# question 2

In [8]:
steps =  np.random.randint(5000,10000,(10))
steps

array([7605, 5751, 5727, 9985, 8995, 8086, 6274, 8585, 6489, 9270],
      dtype=int32)

In [9]:
steps[steps>8000]

array([9985, 8995, 8086, 8585, 9270], dtype=int32)

# question 3

In [7]:
score = np.random.randint(150,200,8)
score

array([185, 187, 172, 180, 181, 185, 191, 159], dtype=int32)

In [12]:
score[[1,4,6]]

array([187, 181, 191], dtype=int32)

# question 4

In [13]:
old_price = np.random.randint(20,1000,20)
old_price

array([615, 390, 246, 647, 676, 955, 920, 959, 894, 891, 267, 998, 573,
       911, 348, 783, 485, 131, 167, 774], dtype=int32)

# question 5

In [15]:
new_price =old_price - old_price * 0.1
new_price

array([553.5, 351. , 221.4, 582.3, 608.4, 859.5, 828. , 863.1, 804.6,
       801.9, 240.3, 898.2, 515.7, 819.9, 313.2, 704.7, 436.5, 117.9,
       150.3, 696.6])