# question 1

In [2]:
import numpy as np
a = np.random.randint(5000,10001,7)
b = np.random.randint(5000,10001,7)
print(a)
print(b)

[9100 5840 8353 6253 5388 8577 8172]
[6314 7241 6440 7137 6002 9790 6173]


In [3]:
add = a+b
add

array([15414, 13081, 14793, 13390, 11390, 18367, 14345], dtype=int32)

In [4]:
sub = a-b
sub

array([ 2786, -1401,  1913,  -884,  -614, -1213,  1999], dtype=int32)

In [5]:
mul =  a*b
mul

array([57457400, 42287440, 53793320, 44627661, 32338776, 83968830,
       50445756], dtype=int32)

In [6]:
div = a/b
div

array([1.44124169, 0.80651844, 1.29704969, 0.87613843, 0.89770077,
       0.87609806, 1.32382958])

# question 2

In [19]:
# a. User Preferences (3 Users x 3 Genres: Pop, Rock, Hip-Hop)
# b. Song Features (3 Genres x 3 Songs: Song X, Song Y, Song Z)
a = np.random.uniform(0.2,1.0,(3,3))
b = np.random.uniform(0.2,1.0,(3,3))
print(a,'\n\n',b)

[[0.30907563 0.42906609 0.50588467]
 [0.61485761 0.26461461 0.41562504]
 [0.64088148 0.81405005 0.49624364]] 

 [[0.34242211 0.98828762 0.37081744]
 [0.48863502 0.35080173 0.63849783]
 [0.507039   0.69832754 0.34453867]]


In [20]:
print("final recomandation : \n\n",np.dot(a,b))

final recomandation : 

 [[0.5719943  0.80924594 0.56286523]
 [0.5505789  0.99072584 0.54015467]
 [0.86884023 1.265486   0.92839434]]


# question 3

In [21]:
img = np.random.uniform(0,1,(4,4))
img

array([[0.80816176, 0.99577812, 0.59749241, 0.62198979],
       [0.69268994, 0.03967191, 0.90076972, 0.46885809],
       [0.4224825 , 0.86055996, 0.18376378, 0.6612815 ],
       [0.12341541, 0.56434382, 0.88029617, 0.14015507]])

In [22]:
img.T

array([[0.80816176, 0.69268994, 0.4224825 , 0.12341541],
       [0.99577812, 0.03967191, 0.86055996, 0.56434382],
       [0.59749241, 0.90076972, 0.18376378, 0.88029617],
       [0.62198979, 0.46885809, 0.6612815 , 0.14015507]])

In [25]:
img.mean()

np.float64(0.5601068717128257)

In [27]:
np.median(img)

np.float64(0.609741101678462)

In [28]:
np.std(img)

np.float64(0.29581003477472073)

In [29]:
np.var(img)

np.float64(0.0875035766734215)

# question 4

In [32]:
np.set_printoptions(formatter={'float': '{:0.2f}'.format})
rating = np.random.uniform(3,5,(3,3))
rating

array([[4.80, 3.16, 4.50],
       [4.24, 4.46, 3.77],
       [4.11, 3.09, 4.32]])

In [33]:
np.linalg.inv(rating)

array([[1.86, 0.06, -1.99],
       [-0.68, 0.55, 0.24],
       [-1.28, -0.44, 1.96]])

In [34]:
np.linalg.det(rating)

np.float64(4.097575070641262)

In [38]:
eigval,eigvactor = np.linalg.eig(rating)
print("eigen values : \n",eigval,"\n\n\neigen vactors : \n",eigvactor)

eigen values : 
 [12.13154968+0.j  0.29344145+0.j  1.15103673+0.j] 


eigen vactors : 
 [[-0.59125613+0.j -0.76388357+0.j  0.4767391 +0.j]
 [-0.59423224+0.j  0.23175921+0.j -0.85288859+0.j]
 [-0.54525611+0.j  0.60230355+0.j  0.21284003+0.j]]


# question 5

In [40]:
orders = np.random.randint(100,201,(2,6))
orders

array([[170, 107, 160, 175, 120, 147],
       [106, 194, 174, 109, 123, 156]], dtype=int32)

In [ ]:
reshaped = np.reshape(orders,(3,4))
reshaped 

array([[170, 107, 160, 175],
       [120, 147, 106, 194],
       [174, 109, 123, 156]], dtype=int32)

In [43]:
orders.flatten()

array([170, 107, 160, 175, 120, 147, 106, 194, 174, 109, 123, 156],
      dtype=int32)

In [48]:
splited = np.split(orders,2)
print(splited)

[array([[170, 107, 160, 175, 120, 147]], dtype=int32), array([[106, 194, 174, 109, 123, 156]], dtype=int32)]


In [51]:
stack = np.stack(splited)
stack

array([[[170, 107, 160, 175, 120, 147]],

       [[106, 194, 174, 109, 123, 156]]], dtype=int32)