# question 1

In [3]:
import numpy as np

playlist_durations = np.array([210, 180, 245, 200, 175])
total_duration = np.sum(playlist_durations)

print(f"Playlist Durations: {playlist_durations} seconds")
print(f"Total Playlist Duration: {total_duration} seconds")

Playlist Durations: [210 180 245 200 175] seconds
Total Playlist Duration: 1010 seconds


# question 2

In [4]:
import numpy as np

# 3 friends (rows) rating 3 Swiggy food items (columns)
ratings_matrix = np.array([
    [5, 4, 3],  # Friend 1
    [3, 5, 2],  # Friend 2
    [4, 4, 5]   # Friend 3
])

print("--- Swiggy Ratings Matrix ---")
print(ratings_matrix)

print("\n--- Ratings for the Second Food Item ---")
second_item_ratings = ratings_matrix[:, 1]
print(second_item_ratings)

--- Swiggy Ratings Matrix ---
[[5 4 3]
 [3 5 2]
 [4 4 5]]

--- Ratings for the Second Food Item ---
[4 5 4]


# question 3

In [6]:
import numpy as np

# 3 days (rows) x 4 dishes (columns)
orders_matrix = np.array([
    [10, 15, 8, 20],  # Day 1
    [12, 18, 5, 22],  # Day 2
    [9,  20, 10, 25]  # Day 3
])

dish_totals = np.sum(orders_matrix, axis=0)

print("--- Total Orders Per Dish Across 3 Days ---")
for i, total in enumerate(dish_totals):
    print(f"Dish {i+1}: {total} orders")

--- Total Orders Per Dish Across 3 Days ---
Dish 1: 31 orders
Dish 2: 53 orders
Dish 3: 23 orders
Dish 4: 67 orders


# question 4

In [7]:
import numpy as np

def calculate_revenue(products_matrix):
    # Multiply column 0 (Price) by column 1 (Quantity)
    revenues = products_matrix[:, 0] * products_matrix[:, 1]
    
    print("--- Total Revenue Per Product ---")
    for index, total in enumerate(revenues):
        print(f"Product {index + 1}: ₹{total}")

# Matrix: [Price (₹), Quantity Sold]
flipkart_data = np.array([
    [500, 10],   # Product 1
    [1200, 5],   # Product 2
    [300, 50],   # Product 3
    [1500, 2],   # Product 4
    [800, 15]    # Product 5
])

calculate_revenue(flipkart_data)

--- Total Revenue Per Product ---
Product 1: ₹5000
Product 2: ₹6000
Product 3: ₹15000
Product 4: ₹3000
Product 5: ₹12000
