# question 1

In [4]:
import numpy as np

# Matrix A: Day 1 data for 2 posts (Rows: Post 1, Post 2. Columns: Likes, Comments)
matrix_a = np.array([
    [100, 15], 
    [250, 40]
])

# Matrix B: Day 2 data for the same metrics
matrix_b = np.array([
    [120, 20], 
    [300, 50]
])

# Perform matrix multiplication using the @ operator
result_matrix = matrix_a @ matrix_b

print("--- Instagram Matrix Multiplication ---")
print("Matrix A (Day 1):\n", matrix_a)
print("\nMatrix B (Day 2):\n", matrix_b)
print("\nResulting Multiplied Matrix:\n", result_matrix)

--- Instagram Matrix Multiplication ---
Matrix A (Day 1):
 [[100  15]
 [250  40]]

Matrix B (Day 2):
 [[120  20]
 [300  50]]

Resulting Multiplied Matrix:
 [[16500  2750]
 [42000  7000]]


# question 2

In [5]:
# Define the function
def linear_regression_predict(x, m, c):
    return (m * x) + c

# Quick test: if x=5, slope(m)=2, intercept(c)=3, y should be 13
test_x = 5
test_m = 2
test_c = 3
result = linear_regression_predict(test_x, test_m, test_c)

print("--- Linear Regression Function Test ---")
print(f"Inputs: x={test_x}, m={test_m}, c={test_c}")
print(f"Predicted y: {result}")

--- Linear Regression Function Test ---
Inputs: x=5, m=2, c=3
Predicted y: 13


# question 3

In [6]:
def linear_regression_predict(x, m, c):
    return (m * x) + c

distances = [2, 5, 8] # in km
slope_m = 4           # 4 minutes per km
intercept_c = 10      # 10 minutes base prep time

print("--- Zomato Delivery Time Predictions ---")
print(f"Using equation: y = {slope_m}x + {intercept_c}\n")

for distance in distances:
    predicted_time = linear_regression_predict(distance, slope_m, intercept_c)
    print(f"Distance: {distance}km  -->  Predicted Delivery Time: {predicted_time} minutes")

--- Zomato Delivery Time Predictions ---
Using equation: y = 4x + 10

Distance: 2km  -->  Predicted Delivery Time: 18 minutes
Distance: 5km  -->  Predicted Delivery Time: 30 minutes
Distance: 8km  -->  Predicted Delivery Time: 42 minutes


# question 4

In [7]:
print("--- Flipkart Price Prediction (Linear Regression) ---\n")

print("1. The Slope (m):")
print("The slope represents the exact amount the price changes for every 1-star increase in the product's rating. If the slope is positive, it means that for every additional star a product earns, its predicted price increases, showing how much premium value a higher rating commands.\n")

print("2. The Intercept (c):")
print("The intercept represents the theoretical starting baseline price of a product if its rating was exactly zero. It acts as the foundational base cost of the item before its customer reputation (rating) influences the final price.")

--- Flipkart Price Prediction (Linear Regression) ---

1. The Slope (m):
The slope represents the exact amount the price changes for every 1-star increase in the product's rating. If the slope is positive, it means that for every additional star a product earns, its predicted price increases, showing how much premium value a higher rating commands.

2. The Intercept (c):
The intercept represents the theoretical starting baseline price of a product if its rating was exactly zero. It acts as the foundational base cost of the item before its customer reputation (rating) influences the final price.


# question 5

In [8]:
print("--- How Matrix Multiplication Powers Spotify ML ---\n")

print("Matrix multiplication allows Spotify's machine learning algorithms to process massive amounts of data simultaneously rather than one by one. By representing millions of users as one matrix and millions of songs as another, the system multiplies them together to instantly calculate predicted preference scores. Because matrix math is highly optimized for modern computers (like GPUs), this allows Spotify to generate personalized recommendations in real-time at a massive scale.")

--- How Matrix Multiplication Powers Spotify ML ---

Matrix multiplication allows Spotify's machine learning algorithms to process massive amounts of data simultaneously rather than one by one. By representing millions of users as one matrix and millions of songs as another, the system multiplies them together to instantly calculate predicted preference scores. Because matrix math is highly optimized for modern computers (like GPUs), this allows Spotify to generate personalized recommendations in real-time at a massive scale.
