# question 1

In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


# question 2

In [4]:
import numpy as np 
Instagram_influencers = np.array([1200, 15000, 67000, 340000, 1250000])
print(Instagram_influencers)
print(Instagram_influencers.shape)
print(Instagram_influencers.ndim)
print(Instagram_influencers.dtype)

[   1200   15000   67000  340000 1250000]
(5,)
1
int64


# question 3

In [8]:
id = np.arange(101,111,1)
print(id)
print(id.size)

[101 102 103 104 105 106 107 108 109 110]
10


# question 4

In [ ]:
like = np.eye(3)
like
# Create a 3x3 identity matrix for the Spotify playlist feature
# The diagonal values (1.0) represent a song's absolute 1:1 self-affinity 
# or direct match score with itself, while off-diagonal zeros indicate 
# independent track relationships.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# question 5

In [10]:
scores = [45, 67, 120, 89, 54]
score = np.array(scores)
print(score.itemsize)

8
